language: node_js
node_js:
- '10'
cache: yarn
script: bash scripts/build.sh
branches:
  only:
    - master
before_install:
- cd frontend
- echo $secret_decrypt_key | gpg --passphrase-fd 0 .env.production.gpg
- cd ../